#!/bin/bash

# Diagnóstico completo de OAuth via Google Cloud API
# Foca no erro "acesso bloqueado" - flowName=GeneralOAuthFlow

PROJECT_ID="ntraining-484414"
PROJECT_NUMBER=$(gcloud projects describe $PROJECT_ID --format="value(projectNumber)" 2>&1)

echo "🔍 DIAGNÓSTICO OAuth - Erro: 'acesso bloqueado'"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Projeto: $PROJECT_ID"
echo "📋 Project Number: $PROJECT_NUMBER"
echo ""

# Obter access token
ACCESS_TOKEN=$(gcloud auth print-access-token 2>&1)
if [[ "$ACCESS_TOKEN" == *"ERROR"* ]] || [ -z "$ACCESS_TOKEN" ]; then
    echo "❌ Erro ao obter access token"
    echo "   Execute: gcloud auth login"
    exit 1
fi

echo "✅ Access token obtido"
echo ""

# Tentar obter informações do OAuth Consent Screen
echo "📋 1. Verificando OAuth Consent Screen..."
echo "   (Pode não retornar dados se não tiver permissões completas)"
echo ""

CONSENT_INFO=$(curl -s -H "Authorization: Bearer $ACCESS_TOKEN" \
    "https://iap.googleapis.com/v1/projects/$PROJECT_NUMBER/iap_web:GetIapSettings" 2>&1)

if [[ "$CONSENT_INFO" == *"error"* ]] || [[ "$CONSENT_INFO" == *"403"* ]] || [[ "$CONSENT_INFO" == *"Permission"* ]]; then
    echo "⚠️  Não foi possível acessar via API (requer permissões IAP)"
    echo "   Usando método alternativo..."
else
    echo "$CONSENT_INFO" | head -30
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 ANÁLISE DO ERRO: 'acesso bloqueado' - flowName=GeneralOAuthFlow"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Este erro indica que o Google está BLOQUEANDO o fluxo OAuth."
echo ""
echo "🔴 CAUSAS MAIS COMUNS (em ordem de probabilidade):"
echo ""
echo "1. ⚠️  OAuth Consent Screen em modo 'Testing'"
echo "   - A tela de consentimento está configurada para 'Testing'"
echo "   - Apenas usuários na lista de 'Test users' podem fazer login"
echo "   - SOLUÇÃO: Adicionar seu email aos test users OU publicar o app"
echo ""
echo "2. ⚠️  Domínios não autorizados"
echo "   - Algum domínio usado não está na lista de 'Authorized domains'"
echo "   - SOLUÇÃO: Adicionar todos os domínios usados na tela de consentimento"
echo ""
echo "3. ⚠️  URLs de redirect incorretas"
echo "   - As URLs de redirect no OAuth client não correspondem"
echo "   - SOLUÇÃO: Verificar e corrigir URLs no OAuth Client"
echo ""
echo "4. ⚠️  Client ID/Secret incorretos no Supabase"
echo "   - Credenciais no Supabase não correspondem ao Google Cloud"
echo "   - SOLUÇÃO: Verificar e atualizar credenciais no Supabase"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ SOLUÇÃO RÁPIDA (passo a passo):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "PASSO 1: Verificar OAuth Consent Screen"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Acesse: https://console.cloud.google.com/apis/credentials/consent?project=$PROJECT_ID"
echo ""
echo "Verifique:"
echo "  □ Status é 'In production' OU"
echo "  □ Se for 'Testing', seu email (resper@ness.com.br) está em 'Test users'"
echo ""
echo "Se estiver em 'Testing' e você NÃO estiver na lista:"
echo "  1. Role até 'Test users'"
echo "  2. Clique em '+ ADD USERS'"
echo "  3. Adicione: resper@ness.com.br"
echo "  4. Clique em 'SAVE'"
echo ""
echo "OU publique o app:"
echo "  1. Role até o final da página"
echo "  2. Clique em 'PUBLISH APP'"
echo "  3. Confirme"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASSO 2: Verificar Domínios Autorizados"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Na mesma página (OAuth Consent Screen), role até 'Authorized domains'"
echo ""
echo "Certifique-se de que contém:"
echo "  □ srrbomtdkghjxdhpeyel.supabase.co"
echo "  □ n-training.vercel.app"
echo "  □ ntraining.ness.com.br"
echo "  □ ness.com.br"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASSO 3: Verificar OAuth Client URLs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Acesse: https://console.cloud.google.com/apis/credentials?project=$PROJECT_ID"
echo ""
echo "Clique no OAuth Client ('n.training Web Client')"
echo ""
echo "Verifique 'Origens JavaScript autorizadas':"
echo "  □ https://srrbomtdkghjxdhpeyel.supabase.co"
echo "  □ https://n-training.vercel.app"
echo "  □ https://ntraining.ness.com.br"
echo ""
echo "Verifique 'URIs de redirecionamento autorizadas':"
echo "  □ https://srrbomtdkghjxdhpeyel.supabase.co/auth/v1/callback"
echo "  □ https://n-training.vercel.app/auth/callback"
echo "  □ https://ntraining.ness.com.br/auth/callback"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASSO 4: Verificar Supabase"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Acesse: https://supabase.com/dashboard/project/srrbomtdkghjxdhpeyel/auth/providers"
echo ""
echo "Verifique:"
echo "  □ Google provider está habilitado (ON)"
echo "  □ Client ID corresponde ao Google Cloud Console"
echo "  □ Client Secret corresponde ao Google Cloud Console"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASSO 5: Testar"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Limpe cookies do navegador (ou use modo anônimo)"
echo "2. Aguarde 2-3 minutos após fazer alterações"
echo "3. Acesse: https://n-training.vercel.app/auth/login"
echo "4. Clique em 'Continuar com Google'"
echo "5. Faça login com: resper@ness.com.br"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 DICA: A causa mais comum (90% dos casos) é a OAuth Consent Screen"
echo "   estar em modo 'Testing' sem o usuário na lista de test users."
echo ""
echo "   Foque primeiro nisso antes de verificar outras configurações."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
